package com.mndeveci.spring.boot.rest;

public interface RetailerQuerries {
	
	/*public static final String JOB_LIST_QUERY = "SELECT  max(distinct(concat(RETAILER_ID,'_',WEEK,'_',YEAR,'_',MONTH,'_',DISCOVERY_START_TIMESTAMP))) COMB,RETAILER_ID,DISCOVERY_STATUS,DISCOVERY_START_TIMESTAMP,DISCOVERY_END_TIMESTAMP,PRE_PROCESSOR_STATUS  FROM JOB_STATUS GROUP BY RETAILER_ID";
	
	public static final String RETAILER_LIST_QUERY = " SELECT RETAILER_ID_G, RETAILER_ID_A,RETAILER_NAME,USER,STATUS"
													+" from RETAILER_INFO ";*/
	public static final String JOB_RETAILER_LIST_QUERY = "select t.RETAILER_TYPE,t.CHECK_STATUS_STORE_TRENDS,t.DISCOVERY_TRANSFER_TIME,t.DISCOVERY_START_TIMESTAMP,t.DISCOVERY_SPLIT_TIME,t.DISCOVERY_SPLIT_SEGMENTS,t.DISCOVERY_STATUS,t.CHECK_STATUS_ITEM_CHECKER,t.CHECK_STATUS_DEPT_TRENDS,t.ANALYST_STATUS,t.FILE_SIZE,t.CHECK_STATUS_DEPT_CHECKER,t.CHECK_STATUS_ZIP_CHECKER,t.CHECK_STATUS_BRAND_CHECKER,t.RETAILER_ID,t.PRE_PROCESSOR_STATUS,ri.RETAILER_NAME,ri.USER_DEFINED_GROUP from RETAILER_INFO ri,(SELECT  max(distinct(concat(RETAILER_ID,'_',WEEK,'_',YEAR,'_',MONTH,'_',DISCOVERY_START_TIMESTAMP))) COMB,DISCOVERY_TRANSFER_TIME,RETAILER_TYPE,JOB_ID,DISCOVERY_SPLIT_TIME,DISCOVERY_SPLIT_SEGMENTS,RETAILER_ID,DISCOVERY_STATUS,DISCOVERY_START_TIMESTAMP,DISCOVERY_END_TIMESTAMP,PRE_PROCESSOR_STATUS ,CHECK_STATUS_BRAND_CHECKER,CHECK_STATUS_ZIP_CHECKER,CHECK_STATUS_DEPT_CHECKER,CHECK_STATUS_DEPT_TRENDS,CHECK_STATUS_ITEM_CHECKER,CHECK_STATUS_STORE_TRENDS,ANALYST_STATUS,FILE_SIZE  FROM JOB_STATUS GROUP BY RETAILER_ID)t WHERE ri.RETAILER_ID_G = t.RETAILER_ID";
	
	public static final String JOB_USER_GROUP = "select distinct(ri.USER_DEFINED_GROUP) from RETAILER_INFO ri,JOB_STATUS js where ri.RETAILER_ID_G = js.RETAILER_ID";//
	
	

	
}
